public class HebrewVerbStemTestDriver 
{
    //test words generated by Chat-GPT
    private static HebrewVerbStemTestCase[] testCases =
{
    new HebrewVerbStemTestCase("לומדת"),
    new HebrewVerbStemTestCase("כותב"),
    new HebrewVerbStemTestCase("כותבת"),
    new HebrewVerbStemTestCase("שומר"),
    new HebrewVerbStemTestCase("שומרת"),
    new HebrewVerbStemTestCase("לומד"),
    new HebrewVerbStemTestCase("לומדת"),
    new HebrewVerbStemTestCase("סוגר"),
    new HebrewVerbStemTestCase("סוגרת"),
    new HebrewVerbStemTestCase("פותח"),
    new HebrewVerbStemTestCase("פותחת"),
    new HebrewVerbStemTestCase("שובר"),
    new HebrewVerbStemTestCase("שוברת"),
    new HebrewVerbStemTestCase("חושב"),
    new HebrewVerbStemTestCase("חושבת"),
    new HebrewVerbStemTestCase("זוכר"),
    new HebrewVerbStemTestCase("זוכרת")
};
    public static void main(String[] args) 
    {
        
        VerbStemFinderPaal stemFinder = new VerbStemFinderPaal();
        int wordCount = 1;
        for(HebrewVerbStemTestCase test : testCases)
        {

            String word = test.input;
            System.out.println("-----TEST " + wordCount + " : " + word + "-----");
            try
            {
                
                stemFinder.findStem(word);
                
            }
            catch(UnrecognizedStemException stemE)
            {
                System.out.println(stemE.getMessage());
            }
            wordCount++;
            System.out.println("");
        }
    }
    
}
